# Generated by Django 2.1.1 on 2018-09-24 01:38

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'o nome do usuario so pode conter letras digitos ou osseguintes caraters:@/./+/-/_', 'invalid')], verbose_name='Apelido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Esta ativo?')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='equipe')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criacao')),
                ('is_accept', models.CharField(default='n', max_length=1, verbose_name='esta oficializado')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
