# Generated by Django 2.1.3 on 2018-11-13 00:33

from django.db import migrations, models
import django.utils.timezone
import functools
import redweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('redweb', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='img',
            field=models.ImageField(blank=True, upload_to=functools.partial(redweb.models.make_filepath, *('media',), **{})),
        ),
    ]
