# Generated by Django 2.1.3 on 2018-11-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redweb', '0004_auto_20181113_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(blank=True, max_length=6000),
        ),
    ]
